### ISSUE TITLE
Fix minerva taxi link

### ISSUE THREAD

**Issue by jeffbaumes** [girder/legacy-resonant-website#1]
This needs a new all-public-data version. See https://github.com/XDATA-Year-3/geoapp/issues/204

**Comment by manthey** [comment]
I've put a public version here http://demo.kitware.com/minerva/ .  I've hidden the messages panel (and the message data is not loaded on the server).  Do we want a different default map?  Or any other default changes?

We should review the TOS of Twitter and Instagram to see if we would be allowed to show geo-searches even if we don't show messages.

**Comment by jeffbaumes** [comment]
This is in a good state for now.
