### ISSUE TITLE
The tangelo and romanesco logos appear differently sized and aligned

### ISSUE THREAD

**Issue by cpatrick** [girder/legacy-resonant-website#2]
I mean, Romanesco is important, but I don't think it's any more important than Tangelo :smile_cat:

**Comment by cpatrick** [comment]
![image](https://cloud.githubusercontent.com/assets/115384/10100741/c7534f1c-6361-11e5-87b8-52e6d469850b.png)

**Comment by cpatrick** [comment]
The more I look at this, I don't know if it's legitimate or an optical illusion.

**Comment by jeffbaumes** [comment]
The tangelo leaves throw everything off. I could make the tangelo logo bigger so the central circular parts are of similar size.

**Comment by cpatrick** [comment]
Yeah, I think that's the right thing.

**Comment by waxlamp** [comment]
I've had this issue with the leaves before.  We could check with Steve about getting rid of them - they cause a lot of problems just like this, and possibly don't contribute a lot to the logo/brand.

**Comment by manthey** [comment]
I like the leaves.  It keeps the logo distinct and provides a pleasant
asymmetry.  I'd rather see a slightly smaller Romanesco logo or leave them
as they are and accept that taneglos are smaller than romanescos.

On Fri, Sep 25, 2015 at 9:26 AM, Roni Choudhury notifications@github.com
wrote:

> I've had this issue with the leaves before. We could check with Steve
> about getting rid of them - they cause a lot of problems just like this,
> and possibly don't contribute a lot to the logo/brand.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Kitware/resonant-website/issues/2#issuecomment-143221934
> .

## 

David Manthey
R&D Engineer
Kitware Inc.
(518) 881-4439

**Comment by zachmullen** [comment]
Option 3: keep the leaves, but make it so the corner of the leaves doesn't go past the top or right of the tangelo, so that the tangelo part can take up the full width and height. The leaves would have to move, and probably have to get a bit smaller...

**Comment by waxlamp** [comment]
Of course, as a fractal vegetable, Romanescos actually exist at every scale.

...that's how fractals work, right guys? :trollface:

**Comment by zachmullen** [comment]
@ronichoudhury I think the largest fractal is actually about 3 inches IIRC.

**Comment by waxlamp** [comment]
@zachmullen not sure what you mean - how can the leaves be in the corner and also not go past the top/right of the tangelo?

**Comment by zachmullen** [comment]
If you placed the leaves at π/4, and made them a bit smaller, you could wedge them into the corner of the image.

**Comment by waxlamp** [comment]
Oh I see, in the middle of the top-right curve of the tangelo skin.  Good idea.

**Comment by jeffbaumes** [comment]
To complicate things further, the logo is actually inside an invisible white circle and would be clipped if outside it - I'm sure we could remove this restriction though with some css.

**Comment by jeffbaumes** [comment]
This is out of date. Closing.
