### ISSUE TITLE
Consider using JPEG rather than PNG for our big header background image

### ISSUE THREAD

**Issue by zachmullen** [girder/legacy-resonant-website#23]
The PNG is 233KB, which can actually take a noticeable amount of time to load. We should be able to make a visually identical JPEG that is much much smaller.

**Comment by manthey** [comment]
Rather, just run optipng or a similar tool on _all_ of the pngs.  The header background can be shrunk to 96 kb with no change in content.

**Comment by jeffbaumes** [comment]
@zachmullen's fix seems fine for the background, even smaller than 96KB and looks good. @manthey if you want to do another PR to make all PNGs smaller that would be great too.
